openapi: 3.0.0
info:
  version: 1.0.0
  title: API Created Service
  description: Service for testing API
  x-cortex-tag: api-created-svc
  x-cortex-owners:
    - type: group
      name: cortex-team
      provider: cortex