##########################################
##      Cortex configuration file       ##
##https://docs.cortex.io/docs/reference ##
##                                      ##
##                                      ##
##                                      ##
##                                      ##
##                                      ##
##########################################

## API Spec and Version
openapi: 3.0.0

# Service Descriptors

# Required fields: info, title, x-cortex-tag
# Optional fields: description
# info:
#   title: <HUMAN_READABLE_SERVICE_NAME>
#   x-cortex-tag: <SERVICE_TAG>
#   description: <DESCRIPTION>
# Add any additional metadata nested under the "info" field to use in Query Builder

# Links

# Required fields: name, type (choose any type you prefer), url
# Optional fields: description
# x-cortex-link:
#   - name: <HUMAN_READABLE_NAME>
#     type: <TYPE>
#     url: <URL_TO_LINK>
#     description: <DESCRIPTION>
#
## Note that type of OPENAPI will be displayed in the API Explorer tab in the Cortex UI
## Links support relative URLs

# Dashboards

# Required fields: type (enumerable field options listed below), url (refers to src of iframe generated in third-party dashboading tool)
# Optional fields: N/A
# x-cortex-dashboards:
# embeds:
#   - type: <datadog | grafana | newrelic>
#     url: <URL>


# Service Groups

# !Service Groups must contain only alphanumeric characters, and may not contain whitespaces!
# Required fields: N/A
# Optional fields: N/A
# x-cortex-service-groups:
#  - <GROUP_NAME>
#  - <GROUP_NAME>
#  - <GROUP_NAME>
#
# Note that hierarchies are only defineable via the API: https://docs.cortex.io/docs/reference/basics/service-groups#api


# Custom Data

# Required fields: N/A
# Optional fields: N/A
# x-cortex-custom-metadata:
  # my-key: the value
  # another-key:
  #   this: is
  #     an: object
  # my-key-2:
  #   value: the actual value for the key
  #   description: This is the description
  # final-key:
  #   - also
  #   - use
  #   - lists!
#
# Note the above is only an example of metadata you may add, not a recommendation. 
# Structure and include data relevant to your organization if desired.

# Dependencies

# Required fields: x-cortex-tag, method (required if path present), path (required if method present)
# Optional fields: description, metadata
# x-cortex-dependency:
#     - tag: <TAG>
#       method: <HTTP_METHOD>
#       path: <PATH_FOR_METHOD>
#       description: <DESCRIPTION>
#       metadata:
#         tags:
#           - <TAG_1>
#           - <TAG_2>
#         prod: true
#
# Note the metadata section above is customizable.

# Integrations

# BambooHR
# x-cortex-owners:
#     - type: group
#       name: <TEAM_NAME>

# Bitbucket
# x-cortex-git:
#   bitbucket:
#     repository: <workspace>/<repo>

# Bugsnag
# x-cortex-bugsnag:
#   project: <PROJECT_KEY> # projectKey in Bugsnag

#Codecov
# x-cortex-static-analysis:
#   codecov:
#     repo: <REPO_NAME> # git repo, with org and repo name
#     provider: <GITHUB | GITLAB | BITBUCKET> # select one of the three options

#Datadog
# x-cortex-apm:
#   datadog:
#     serviceTags: # List of tags & values
#       - tag: <KEY>
#         value: <VALUE>
#       - tag: <KEY>
#         value: <VALUE>
#     monitors:
#         - <MONITOR_ID>
#         - <MONITOR_ID_2>
# x-cortex-slos:
#     datadog: # List of SLO ids
#       - id: <SLO_ID>
#       - id: <SLO_ID_2>

# AWS ECS
# x-cortex-infra:
#   aws:
#     ecs:
#       - clusterArn: <CLUSTER_ARN>
#         serviceArn: <SERVICE_ARN>
#       - clusterArn: <CLUSTER_ARN_2>
#         serviceArn: <SERVICE_ARN_2>

# Github
# x-cortex-git:
#   github:
#     repository: <org>/<repo>
#     basepath: <SERVICE_NAME> # optional
# x-cortex-owners:
#   - type: group
#     name: <ORGANIZATION>/<TEAM> # Must be of form <org>/<team>


# Gitlab
# x-cortex-git:
#   gitlab:
#     repository: <namespace>/<project>
#     basepath: <SERVICE_NAME> # optional
# x-cortex-owners:
#   - type: group
#     name: <GROUP_NAME>

# Google
# x-cortex-owners:
#   - type: group
#     name: <GROUP_NAME>

# Grafana
# x-cortex-dashboards:
#   embeds:
#     - type: grafana
#       url: <FULL_URL_TO_DASHBOARD>

# Jira
# x-cortex-issues:
#   jira:
#     labels:
#       - <LABEL1>
#       - <LABEL2>
#     components:
#       - <COMPONENT1>

# Kubernetes
# info:
#   title: <HUMAN_READABLE_SERVICE_NAME>
#   x-cortex-tag: <SERVICE_TAG>
#   description: <DESCRIPTION>

# Lightstep
# x-cortex-slos:
#   lightstep:
#     - streamId: <STREAM_ID>
#       targets:
#       latency:
#         - percentile: <PERCENTILE>
#           target: <TARGET>
#           slo: <SLO>

# New Relic
# x-cortex-apm:
#   newrelic:
#     applicationId: <APP_ID>
# x-cortex-dashboards:
#   embeds:
#     - type: newrelic
#       url: <FULL_URL_TO_DASHBOARD>

# Okta
# x-cortex-owners:
#   - type: group
#     name: <GROUP_NAME> # group name in Okta

# OpsGenie
# x-cortex-oncall:
#   opsgenie:
#     type: SCHEDULE
#     id: <SCHEDULE_ID> # Optionally, can use the Rotation UUID instead
# x-cortex-owners:
#   - type: group
#     name: <GROUP_NAME>
# x-cortex-alerts:
#   - type: opsgenie
#     tag: <KEY>
#     value: <VALUE>

#Pagerduty
# x-cortex-oncall:
#   pagerduty:
#     id: <SERVICE_ID> # Service ID
#     type: SERVICE
# x-cortex-oncall:
#   pagerduty:
#     id: <SCHEDULE_ID> # Schedule ID
#     type: SCHEDULE
# x-cortex-oncall:
#   pagerduty:
#     id: <POLICY_ID> # Escalation Policy ID
#     type: ESCALATION_POLICY

# Rollbar
# x-cortex-rollbar:
#   project: <PROJECT_NAME> # projectName in Rollbar

# Sentry
# x-cortex-sentry:
#   project: <PROJECT_NAME> # projectName in Sentry

# SignalFX
# x-cortex-slos:
#   signalfx:
#     - query: <FULL_SFX_QUERY>  # Ex. sf_metric:"jvm.memory.max" AND area:"nonheap"
#       rollup: <ROLLUP>
#       target: <TARGET>
#       lookback: <LOOKBACK>
#       operation: <OPERATION>

# Slack
# x-cortex-owners:
#   - type: slack
#     channel: <CHANNEL_NAME>
# Note: list Slack channels, *without* the preceeding "#"

# Snyk
# x-cortex-snyk:
#   projects:
#     - organizationId:<ORGANIZATION_ID>
#       projectId: <PROJECT_ID>

# Sonarqube
# x-cortex-static-analysis:
#   sonarqube:
#     project: <PROJECT_KEY> # projectKey in SonarQube

# VictorOps
# x-cortex-oncall:
#   victorops:
#     type: SCHEDULE
#     id: <SCHEDULE_ID>